name: NPM Publish
run-name: Check new version and publish

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    steps:
      - uses: actions/checkout@v3
      - id: version
        uses: EndBug/version-check@v2.1.1
        with:
          file-url: https://unpkg.com/@appsignal/opentelemetry-instrumentation-bullmq@latest/package.json
          static-checking: localIsNew
      - name: Use Node.js
        if: steps.version.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install
        if: steps.version.outputs.changed == 'true'
        run: npm ci
      - name: Build
        if: steps.version.outputs.changed == 'true'
        run: npm run build
      - name: NPM Publish
        if: steps.version.outputs.changed == 'true'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
